"""
Generates a MERGE-based SQL script to populate the Workweek table for a
given year range. Standalone stdlib script (no pyodbc/Azure Functions
runtime needed) -- reuse this directly to extend Workweek to future years,
e.g.:

    python3 generate_workweek_sql.py 2031 2035 > "../sql/Workweek/Populate 2031-2035.sql"

Convention (see sql/Workweek/Create tbl Workweek.sql for the full writeup):
  - Week 1 of year Y starts on the Sunday on-or-before January 1 of Y, so
    January 1st always falls within Week 1 (this can dip a few days into
    December of the PREVIOUS year).
  - Each year is anchored independently to its own January 1 -- there's no
    continuous rolling week counter across years.
  - Weeks are always exactly 7 days (Sunday through Saturday). Since
    52 x 7 = 364 days and a year has 365/366, the last 2-8 days of
    December (depending on what weekday January 1 falls on that year)
    aren't covered by that year's 52 weeks -- they become part of the
    FOLLOWING year's Week 1 instead. No calendar date is ever left
    completely uncovered; it just sometimes lands under the "next" year's
    label.
"""

import sys
from datetime import date, timedelta

WEEKS_PER_YEAR = 52


def sunday_on_or_before(d: date) -> date:
    """The Sunday on or before d (returns d itself if d is already a Sunday)."""
    offset = (d.weekday() + 1) % 7  # Python: Monday=0 .. Sunday=6
    return d - timedelta(days=offset)


def generate_rows(start_year: int, end_year: int):
    """Yields (year, week, start_date, end_date) tuples for start_year..end_year inclusive."""
    for year in range(start_year, end_year + 1):
        week1_start = sunday_on_or_before(date(year, 1, 1))
        for week in range(1, WEEKS_PER_YEAR + 1):
            start = week1_start + timedelta(weeks=week - 1)
            end = start + timedelta(days=6)
            yield (year, week, start, end)


def generate_merge_sql(start_year: int, end_year: int) -> str:
    rows = list(generate_rows(start_year, end_year))

    values_lines = ",\n".join(
        f"    ({year}, {week}, '{start.isoformat()}', '{end.isoformat()}')"
        for year, week, start, end in rows
    )

    return f"""-- Auto-generated by scripts/generate_workweek_sql.py {start_year} {end_year}
-- Idempotent: safe to re-run. Existing (Year, Week) rows get their dates
-- refreshed to match; new ones get inserted. Doesn't touch rows for years
-- outside {start_year}-{end_year}.
MERGE Workweek AS target
USING (VALUES
{values_lines}
) AS source (Year, Week, StartDate, EndDate)
ON target.Year = source.Year AND target.Week = source.Week
WHEN MATCHED THEN UPDATE SET
    StartDate = source.StartDate,
    EndDate   = source.EndDate
WHEN NOT MATCHED THEN
    INSERT (Year, Week, StartDate, EndDate)
    VALUES (source.Year, source.Week, source.StartDate, source.EndDate);
"""


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 generate_workweek_sql.py <start_year> <end_year>", file=sys.stderr)
        sys.exit(1)
    print(generate_merge_sql(int(sys.argv[1]), int(sys.argv[2])))
