SELECT TOP (1000) [Id]
      ,[Name]
      ,[Environment]
      ,[StartDateTime]
      ,[EndDateTime]
      ,[TotalSuccessfulRecords]
      ,[TotalErrorRecords]
      ,[Source]
      ,[BatchIds]
      ,[BatchCount]
      ,[IsFinalBatch]
      ,[ErrorMessage]
  FROM [dbo].[SP_Execution]